- dask_groupby/core.py
- tests/test_core.py
@dcherian, let me know whether we should add more tests for `xarray_groupby_reduce`
> Fix input and output core dims

- dask_groupby/__init__.py
- dask_groupby/core.py
- dask_groupby/xarray.py
- tests/__init__.py
- tests/test_core.py
- tests/test_xarray.py
> Move xarray interface to a separate module

- dask_groupby/core.py
- tests/test_xarray.py
> Properly set token for blockwise reduction

- ci/environment.yml
- dask_groupby/core.py
- dask_groupby/xarray.py
- requirements.txt
- tests/test_core.py
- tests/test_xarray.py
> Add cohorts strategy

- flox/core.py
- flox/xarray.py
- tests/test_core.py
- tests/test_xarray.py
Closes #69.
Same idea but plugged in to current infrastructure
> blockwise + reduction approach as a special combine/agg stage

- docs/source/user-stories/climatology-hourly.ipynb
- flox/core.py
- tests/test_core.py
Promote to int like xarray.
Closes #100
Closes https://github.com/pydata/xarray/issues/6615
> Fix reductions on boolean reductions.

- flox/aggregate_flox.py
- tests/test_xarray.py
> Use isnull instead of isnan: engine="flox"

- flox/xarray.py
- tests/test_xarray.py
Closes https://github.com/pydata/xarray/issues/6616
> Fix grouping by multiindex

- flox/xarray.py
- flox/xrutils.py
- tests/test_xarray.py
Copy over a bunch of xarray code.
Closes https://github.com/pydata/xarray/issues/6613
> Convert datetimes to numeric.

- flox/core.py
- flox/xarray.py
- tests/test_core.py
- tests/test_xarray.py
> Fix reduction along dimensions not in groupers.

- docs/source/user-stories.md
- docs/source/user-stories/overlaps.md
> Add Overlapping trick to docs.

- tests/test_core.py
> Fix test failure on 32bit architectures

- .pre-commit-config.yaml
Is this the way to get the pre-commit bot to update often, like https://github.com/pydata/xarray/pull/7056?
> Get pre-commit bot to update

- flox/xarray.py
- tests/test_xarray.py
> Deprecate resample_reduce

- flox/aggregations.py
- flox/core.py
- flox/xarray.py
- tests/test_core.py
- tests/test_xarray.py
> Suppress warnings

- tests/test_core.py
> 32bit support: int64 to intp for count

- tests/test_core.py
> 32bit: More intp fixes

- asv_bench/benchmarks/reduce.py
> add expected groups benchmark

- asv_bench/benchmarks/reduce.py
- flox/core.py
- tests/test_core.py
pd.cut is rather slow, use np.digitize instead.
> Use np.digitize instead of pd.cut

- flox/core.py
- flox/xarray.py
- pyproject.toml
- tests/test_core.py
> Add more type hints

- flox/core.py
- tests/test_core.py
~5-10% improvement on xarray benchmarks
> Always reindex=True for all numpy inputs

- ci/environment.yml
- ci/minimal-requirements.yml
- ci/no-dask.yml
- ci/no-xarray.yml
- ci/upstream-dev-env.yml
- flox/core.py
- tests/conftest.py
- tests/test_core.py
> Always factorize early

- flox/core.py
> Fix test failure on i386

- flox/xarray.py
- flox/xrutils.py
This makes datetime conversions a tiny bit faster.
> convert datetime: micro-optimizations

- .pre-commit-config.yaml
- .readthedocs.yml
- flox/visualize.py
- pyproject.toml
> repo-review comments

- asv_bench/benchmarks/reduce.py
- flox/core.py
> Actually optimize out multiple "nanlen"

- flox/xarray.py
- tests/test_xarray.py
Closes https://github.com/pydata/xarray/issues/8292
> Fix reordering of dataarray dimensions inside dataset

- asv_bench/benchmarks/cohorts.py
- docs/source/user-stories/climatology.ipynb
- flox/core.py
- tests/test_xarray.py
Closes https://github.com/pydata/xarray/issues/8592
> Fix missing resampling groups.

- flox/core.py
- tests/test_core.py
> cohorts: Delete the merge kwarg

- ci/minimal-requirements.yml
- flox/core.py
- pyproject.toml
- tests/test_core.py
> Be more strict with requirements: scipy, pandas

- ci/environment.yml
- ci/no-dask.yml
- flox/aggregate_numbagg.py
- flox/aggregations.py
Needs https://github.com/numbagg/numbagg/pull/268 to be released
> Pass ddof through for numbagg

- .github/workflows/upstream-dev-ci.yaml
- flox/xarray.py
- tests/test_core.py
> Fix upstream-dev CI, silence warnings

- flox/aggregate_flox.py
- flox/aggregate_npg.py
- flox/aggregate_numbagg.py
- tests/test_core.py
Closes https://github.com/pydata/xarray/issues/8853
> Fix nanlen with strings

- asv_bench/asv.conf.json
https://github.com/airspeed-velocity/asv/issues/1389#issuecomment-2076131185
> Fix benchmarks

- tests/test_properties.py
now that https://github.com/ml31415/numpy-groupies/pull/90 was merged
> Stricter tolerance in property tests

- flox/aggregate_numbagg.py
- flox/core.py
- flox/xarray.py
- flox/xrutils.py
- tests/test_core.py
This reverts commit 4f6164f74a657d95f795c374e31e91a7e7643e9f.
xref #403
> Revert "Support first, last with datetime, timedelta (#402)"

- tests/conftest.py
> remove engine="numba" from tests

- asv_bench/benchmarks/combine.py
- flox/__init__.py
- flox/core.py
- flox/xarray.py
- pyproject.toml
- tests/__init__.py
- tests/test_core.py
> Allow reindexing to sparse

- .github/workflows/upstream-dev-ci.yaml
- ci/env-numpy1.yml
- ci/environment.yml
- ci/no-dask.yml
- ci/no-numba.yml
- ci/no-xarray.yml
- docs/source/arrays.md
- flox/aggregate_flox.py
- flox/aggregate_sparse.py
- flox/aggregations.py
- flox/core.py
- flox/lib.py
- flox/xrutils.py
- tests/__init__.py
- tests/strategies.py
- tests/test_core.py
- tests/test_properties.py
> Support aggregating sparse arrays.
