xarray-contrib/flox

- ci/environment.yml
- flox/cache.py
- flox/core.py
- setup.cfg
- tests/test_core.py
Closes #51
Can't use lru_cache because numpy arrays are not hashable.
> Support caching of cohorts with cachey.

- flox/core.py
- flox/xarray.py
- tests/test_core.py
> Support cohorts for nD `by` arrays

- docs/source/user-stories/climatology-hourly.ipynb
- flox/core.py
- tests/test_core.py
agg.finalize was set to None when blockwise, this
wouldn't work when followed by map-reduce
Closes #102
> Fix mixing of blockwise and map-reduce strategies.

- flox/core.py
- tests/test_xarray.py
Affects _factorize_multiple, groupby_reduce, to fix xarray support.
Closes https://github.com/dcherian/flox/pull/111 .
> Fix extra expected groups

- flox/core.py
- tests/test_xarray.py
This affected _factorize_multiple.
Closes #111
Thanks to @LunarLanding for reporting
> Fix bug where we had extra groups in expected_groups.

- flox/core.py
- tests/test_core.py
> Allow custom numpy aggregations for "blockwise"

- ci/docs.yml
- ci/environment.yml
- ci/minimal-requirements.yml
- ci/no-dask.yml
- ci/no-xarray.yml
- flox/aggregate_flox.py
- flox/aggregations.py
- flox/core.py
- flox/xarray.py
- flox/xrutils.py
- setup.cfg
xref #128 
This really only works with engine="numpy" for anything that uses `bincount` (mean, sum, std, var) and when we are grouping by a numpy array.
So something like `groupby("time.month").mean(engine="numpy")`
> Support duck arrays by default

- flox/xarray.py
- tests/test_xarray.py
This fixes #137.
- Generalized the datetime reduce test so it tests all engines.
- When `func='count'` and `engine != 'flox'`, `requires_numeric` becomes True, which avoid type errors in numba and numpy.
The "flox" engine is not included because I saw a loss of performance in my (small) tests. 
```python3
import xarray as xr
from flox.xarray import xarray_reduce
t = xr.DataArray(xr.cftime_range('1900-01-01', periods=100000, freq='H'), dims=('time',))
xarray_reduce(t, t.dt.month, func='count', engine=ENGINE)
```
With engine 'flox', this code was around 10% slower if I added the numeric conversion.
> Fix func count for dtype O with numpy and numba

- .github/workflows/ci-additional.yaml
- ci/environment.yml
- flox/xarray.py
Add doctest and mypy. Mypy fails at the moment so deactivate it for now, can be temporarily activated to check if errors are reduced.
> Add ci additional

- flox/xarray.py
The duplicate headers crashed the docs.
> Remove duplicate Examples headers

- flox/xarray.py
- tests/test_xarray.py
> can you open a separate PR to raise an error here when `len(by) > 1`
> 
> _Originally posted by @dcherian in https://github.com/xarray-contrib/flox/pull/144#discussion_r975827289_
> Raise error if multiple by's are used with Ellipsis

- flox/core.py
- flox/xarray.py
Simplifies typing and the `raise_if_dask` argument was only used once.
> Remove None output from _get_expected_groups

- flox/core.py
A performance improvement and seems to fix some mypy errors seen in #150 as well.
Example:
```python
%timeit math.prod((1, 2, 3))
161 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
%timeit int(np.prod((1, 2, 3)))
11.9 µs ± 248 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
xref: https://github.com/pydata/xarray/pull/6765
> Use math.prod instead of np.prod

- flox/core.py
- flox/xarray.py
- tests/__init__.py
- tests/test_core.py
Check taken from: `da.utils.assert_eq(a, b, equal_nan=True)`
> Add a dtype check for numpy arrays in assert_equal

- flox/aggregations.py
- flox/core.py
- flox/xarray.py
- tests/__init__.py
- tests/test_core.py
- tests/test_xarray.py
Closes https://github.com/pydata/xarray/issues/6902
cc @Illviljan @tasansal
> Allow specifying output dtype

- docs/source/implementation.md
- flox/core.py
- flox/visualize.py
- flox/xarray.py
- tests/test_core.py
Closes #140
We apply the cohort "split" step after the blockwise reduction, then use
the tree reduction on each cohort.
We also use the `.blocks` accessor to index out blocks. This is still a
bit inefficient since we split by indexing out regular arrays, so we
could index out blocks that don't contain any cohort members. However,
because we are splitting _after_ the blockwise reduction, the amount of
work duplication can be a lot less than splitting the bare array.
One side-effect is that "split-reduce" is now a synonym for "cohorts".
The reason is that find_group_cohorts returns a dict mapping blocks to
cohorts. We could invert that behaviour but I don't see any benefit to
trying to figure that out.
> More efficient cohorts.

- flox/core.py
- flox/xarray.py
- tests/test_core.py
> Remove split_out

- asv_bench/benchmarks/cohorts.py
- flox/__init__.py
- flox/cache.py
- flox/core.py
> Performance improvements for cohorts detection

- asv_bench/benchmarks/cohorts.py
- flox/core.py
- tests/__init__.py
- tests/test_core.py
Turns out I wasn't actually subsetting in many cases so we were just repeatedly computing over the entire array for every cohort (!)
Incredibly bad regression!
> Major fix to subset_to_blocks

- flox/core.py
- tests/test_core.py
Closes #155
Turns out we weren't using the more efficient `simple_combine` with `map-reduce` in all cases because `do_simple_combine` was None when reindex was None.
Now the default for `map-reduce` is `reindex=True` when (`expected_groups is not None`) or (`expected_groups is None and by_is_dask is False`)
> Force reindex to be bool always

- asv_bench/benchmarks/combine.py
- flox/core.py
- tests/test_core.py
This PR allows reindexing inside `_simple_combine` so that we don't need to rerun
the groupby-reduce at every combination stage.
This means we are down to three options (good improvement!)
1. `map-reduce` with `reindex=True`: reindex to expected_groups at blockwise stage, then map-reduce
2. `map-reduce` with `reindex=False`: reindex at combine stage of map-reduce
3. `cohorts`  : start with `reindex=False` at blockwise, and then reindex to cohorts specifically, then tree reduce with `reindex=True`
For 1D combine, we see great improvements for `reindex=True`
`reindex=False` uses 2x more memory but similar time.
Note that the `reindex=False` intermediates are a worst case where there are
no shared groups between the chunks being combined.
This case is actually optimized in `_group_combine` …
> Support reindexing in simple_combine

- asv_bench/benchmarks/cohorts.py
- flox/core.py
- flox/xarray.py
- tests/test_core.py
Save some time spent factorizing unnecessary values.
TODO:
> Avoid broadcasting by variables against each other

- flox/core.py
- flox/xarray.py
- tests/test_xarray.py
> Better alignment check + error

- flox/core.py
- flox/xarray.py
- tests/test_core.py
- tests/test_xarray.py
> Consolidate validation of expected_groups

- flox/core.py
- tests/test_core.py
with multiple groupers, multiple reductions.
> Fix race condition in factorize

- tests/__init__.py
`tests/__init__.py` still uses the deprecated distutils which will be removed in Python 3.12.
From [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated):
> The entire `distutils` package is deprecated, to be removed in Python 3.12. Its functionality for specifying package builds has already been completely replaced by third-party packages `setuptools` and `packaging`, and most other commonly used APIs are available elsewhere in the standard library (such as [platform](https://docs.python.org/3/library/platform.html#module-platform), [shutil](https://docs.python.org/3/library/shutil.html#module-shutil), [subprocess](https://docs.python.org/3/library/subprocess.html#module-subprocess) or [sysconfig](https://docs.python.org/3/library/sysconfig.html#mod …
> Don't use deprecated distutils module.

- flox/xarray.py
- tests/test_xarray.py
xref https://github.com/pydata/xarray/issues/7730
> Optimize broadcasting

- flox/aggregations.py
- flox/core.py
- flox/xrutils.py
- tests/test_core.py
> Support nanfirst, nanlast with simple combine algo

- asv_bench/benchmarks/cohorts.py
- asv_bench/benchmarks/combine.py
- pyproject.toml
- tests/test_core.py
Fix some typing issues in the `asv_bench` and `tests` folders. Also allow mypy to check these folders.
> Fix some typing errors in asv_bench and tests

- .github/workflows/upstream-dev-ci.yaml
- flox/xrdtypes.py
`numpy` version 2 will introduce a few breaking changes, one of which `flox` inherited from `xarray`: the use of `np.unicode_` instead of `np.str_`.
Edit: the `mypy` error should be unrelated
Edit2: this is currently blocking pydata/xarray#8117 (as noted there: `numpy` appears to be a bit unstable as they prepare for the 2.0 release, so not sure how quickly we need to adapt)
> compatibility with `numpy>=2.0`

- tests/__init__.py
- tests/conftest.py
- tests/test_core.py
- tests/test_xarray.py
I had a look at the flox tests and moved the xfails out of the function body. This is marginally faster as the skipping happens at collection time.
(It's is certainly not worth it but I couldn't sleep..., let me know if any of them look too ugly)
> tests: move xfail out of functions

- asv_bench/benchmarks/cohorts.py
- flox/core.py
Closes #271 
I was iterating over `array.blocks` to figure out the shape of each chunk.
When indexing this object, it creates a dask array per chunk, which is slow for many reasons
- dask array construction, which is useless
- calling np.array() on a chunks tuple repeatedly in a loop (surprisingly slow!)
Replace with a function that calculates the chunk shape. On the arco era5 with 93044 time chunks, this is a speedup from infinite time to 840ms.
```python
TIME = 92044
da = xr.DataArray(
dask.array.ones((TIME, 721, 1440), chunks=(1, -1, -1)),
dims=("time", "lat", "lon"),
coords=dict(time=pd.date_range("1959-01-01", freq="6H", periods=TIME)),
)
%time xarray_reduce(da, da.time.dt.day, method="cohorts", func="any")
```
> Significantly faster cohorts detection.

- asv_bench/benchmarks/reduce.py
- flox/core.py
- tests/test_core.py
This majorly improves the `dim=...` case for `engine="flox"` at least. xref https://github.com/xarray-contrib/flox/issues/281
I'm not sure if it is a regression for `engine="numpy"`: EDIT it is a small regression, but a big one for `engine="numbagg"` (9ms -> 27ms).
We trade off a single bad reshape for `array` against argsorting both `array` and `group_idx` for a ~10-20x speedup
```
ds = xr.tutorial.load_dataset('air_temperature')
ds.groupby('lon').count(..., engine="flox")
```
> Set order='F' when raveling group_idx after broadcast

- asv_bench/benchmarks/reduce.py
- flox/aggregate_numbagg.py
- flox/aggregations.py
- flox/core.py
- flox/xrutils.py
- pyproject.toml
- tests/test_core.py
- tests/test_xarray.py
Closes #281
1. fix version check
2. Handle fill_value for numbagg.
3. enable numbagg for count
TODO:
> Fix numbagg aggregations

- asv_bench/benchmarks/cohorts.py
- asv_bench/benchmarks/reduce.py
- flox/core.py
- tests/test_core.py
xref #180
Containment = |Q & S| / |Q|
where
- |X| is the cardinality of set X
- Q is the query set being tested
- S is the existing set
https://ekzhu.com/datasketch/lshensemble.html#containment
> Use set containment instead of perfect subsets

- asv_bench/benchmarks/cohorts.py
- flox/core.py
Expected for some resampling workloads
In the future, we should automatically choose blockwise for the user.
```
| Change   | Before [bf936f52] <main>   | After [1f51a343] <cohorts-blockwise-opt>   |   Ratio | Benchmark (Parameter)                                      |
|----------|----------------------------|--------------------------------------------|---------|------------------------------------------------------------|
| -        | 1.86±0.06ms                | 651±10μs                                   |    0.35 | cohorts.PerfectBlockwiseResampling.time_find_group_cohorts |
```
> Optimize cohorts for blockwise distribution of groups

- flox/core.py
- tests/test_core.py
> Use mock instead of testing for strings in layer.

- asv_bench/benchmarks/cohorts.py
- flox/core.py
Skips finding the `max` of labels, since we already know that. Finding the max takes 30% of the time for the NWM groupby
> Pass expected_groups to find_group_cohorts.

- flox/core.py
```
| Before [e26fb39e] <main>   | After [9753dfea] <optimize-again>   |   Ratio | Benchmark (Parameter)                                      |
|----------------------------|-------------------------------------|---------|------------------------------------------------------------|
| 4.10±0.05ms                | 3.64±0.04ms                         |    0.89 | cohorts.ERA5MonthHour.time_find_group_cohorts              |
| 4.56±0.05ms                | 4.00±0.06ms                         |    0.88 | cohorts.ERA5MonthHourRechunked.time_find_group_cohorts     |
| 3.31±0.08ms                | 2.79±0.01ms                         |    0.84 | cohorts.ERA5DayOfYear.time_find_group_cohorts              |
| 8.15±0.05ms                | 6.78±0.02ms                         |    0.83 | …
```
> Optimize bitmask finding some more.

- flox/aggregate_flox.py
- flox/core.py
Closes #334 
Now a 50% speedup over a simple for loop over groups as opposed to a 50% slowdown.
```python
shape = (31411, 25, 25, 1)
import pandas as pd
import xarray as xr
time = pd.date_range("2014-01-01", "2099-12-31", freq="D")
da = xr.DataArray(
np.random.randn(*shape),
name="pr",
dims=("time", "lat", "lon", "lab"),
coords={"time": time},
)
rs = da.resample(time="YE")
%timeit rs.quantile(q=0.9);
%timeit flox.xarray.xarray_reduce(da, rs._codes, engine="flox", func="quantile", q=0.9);
```
> quantiles use complex array partition, not lexsort

- flox/xarray.py
- tests/__init__.py
- tests/test_core.py
- tests/test_xarray.py
Closes https://github.com/pydata/xarray/issues/8819
> Fix direct reductions of Xarray objects

- asv_bench/benchmarks/cohorts.py
- ci/benchmark.yml
- docs/source/implementation.md
- flox/core.py
Spotted another possible optimization
xref #346
Annoyingly `asv` is broken and not running now but in a notebook:
Even better now since we can use `sparsity(bitmask)` as a proxy instead of `sparsity(containment)` This avoids an expensive sparse matrix dot product when `bitmask` isn't particularly sparse:
> `method` heuristics: Avoid dot product as much as possible

- asv_bench/benchmarks/cohorts.py
- flox/core.py
- tests/test_core.py
1. With size-1 chunks, we needn't find unique labels in each chunk. There's only one label in each chunk!
2. When there is only a single chunk, we should just run `blockwise`.
```
| Before [497e7bc1] <main> | After [4935636b] | Ratio | Benchmark (Parameter)                       |
|--------------------------+------------------+-------+---------------------------------------------|
| 876±6μs                  | 640±80μs         |  0.73 | cohorts.SingleChunk.time_graph_construct    |
| 1.86±0.01ms              | 229±30μs         |  0.12 | cohorts.ERA5Google.time_find_group_cohorts  |
| 329±10μs                 | 1.58±0.1μs       |     0 | cohorts.SingleChunk.time_find_group_cohorts |
```
> Optimize bitmask finding for chunk size 1 and single chunk cases

- ci/docs.yml
- docs/source/user-stories.md
- docs/source/user-stories/climatology-hourly-cubed.ipynb
> Add cubed notebook for hourly climatology example using "map-reduce" method

- asv_bench/benchmarks/cohorts.py
- flox/core.py
- tests/test_core.py
Since cubed is implementing its own code path, I think its OK to optimize to this degree.
```
| Change   | Before [627bf2b6] <main>   | After [9d710529] <optimize-cohorts-graph>   |   Ratio | Benchmark (Parameter)                           |
|----------|----------------------------|---------------------------------------------|---------|-------------------------------------------------|
| -        | 3.39±0.02ms                | 2.98±0.01ms                                 |    0.88 | cohorts.PerfectMonthly.time_graph_construct     |
| -        | 20                         | 17                                          |    0.85 | cohorts.PerfectMonthly.track_num_layers         |
| -        | 23.0±0.07ms                | 19.0±0.1ms                                  |    0.83 | …
```
> Manually fuse reindexing intermediates with blockwise reduction for cohorts.

- flox/core.py
xref #363 
Skip reindexing when `expected_groups` is *not* provided. In this case, we detect all available groups anyway.\
This is less impactful than it seems because Xarray *always* sets `expected_groups = (pd.RangeIndex(...),)`.
A solution is to set `min_count=0` upstream for `UniqueGrouper`
> Optimize `min_count` when `expected_groups` is not provided.

- flox/xrutils.py
This currently emits a warning, not an error (i.e. not that urgent), but I did notice this a couple of times in `xarray`'s CI.
I'm not too happy about having to move the definition of `module_available` above the import (`isort` might revert that?), but I didn't know whether it would be fine to move that function to a separate module (*and* I was too lazy to try figuring out a good name for that module).
> import `normalize_axis_index` from `numpy.lib` on `numpy>=2`

- ci/environment.yml
- docs/source/user-stories/climatology-hourly-cubed.ipynb
- flox/core.py
- tests/test_core.py
Fixes #354
Relies on https://github.com/cubed-dev/cubed/pull/448
> Cubed blockwise

- .github/workflows/ci.yaml
- flox/aggregate_flox.py
- flox/aggregations.py
- flox/core.py
- flox/xrdtypes.py
- tests/__init__.py
- tests/conftest.py
- tests/strategies.py
- tests/test_core.py
- tests/test_properties.py
- tests/test_xarray.py
Closes #29
1. Adds coverage for `first` and `last`.
2. Fixes `not_overflowing_array` to work with NaNs! This is a big one.
3. Add more array dtypes to more tests.
4. Turns out `bfill` was quite broken!
5. refactor out hypothesis strategies
> Expand property tests

- flox/__init__.py
- flox/core.py
- tests/conftest.py
- tests/test_core.py
- tests/test_properties.py
> Fix first, last again

- flox/aggregate_flox.py
- flox/aggregations.py
- flox/xrdtypes.py
- tests/test_core.py
> Avoid explicit np.nan, np.inf

- flox/core.py
- tests/test_core.py
xref https://github.com/pydata/xarray/pull/9320
> Fix bug with NaNs in `by` and method='blockwise'

- flox/core.py
xref #396
Big improvement but still scales linearly with number of cohorts.
```
1736      3650     426000.0    116.7      0.0                  reindexer = (
1737      3650    1115000.0    305.5      0.0                      partial(reindex_intermediates, agg=agg, unique_groups=cohort_index)
1738      3650     609000.0    166.8      0.0                      if do_simple_combine
1739                                                               else identity
1740                                                           )
1741      3650  885572000.0 242622.5     20.6                  reindexed = subset_to_blocks(intermediate, blks, block_shape, reindexer, chunks_as_array)
1742                                                           # now that we have reindexed, we can set reindex=True …
```
> Faster subsetting for cohorts

- .github/workflows/ci.yaml
- ci/env-numpy1.yml
- ci/environment.yml
- ci/no-dask.yml
- ci/no-numba.yml
- flox/aggregations.py
- flox/core.py
This reverts commit 4a59ffa2cdfcb2d4fc662f451d153d68cf77a5b2.
> Revert "[revert] test with Xarray PR branch"

- flox/aggregate_numbagg.py
- flox/core.py
- flox/xarray.py
- flox/xrutils.py
- tests/test_core.py
> Support first, last with datetime, timedelta

- flox/core.py
- tests/test_core.py
@tomwhite the latest cubed release seems. to have broken a few things.
> Xfail some cubed tests

- ci/docs.yml
- ci/env-numpy1.yml
- ci/environment.yml
- tests/test_core.py
Cubed 0.20.0 supports Zarr Python v3 (https://github.com/cubed-dev/cubed/pull/656), and fixes the bug in groupby (https://github.com/cubed-dev/cubed/pull/669).
> Cubed fixes

- flox/core.py
- flox/dask_array_ops.py
- tests/test_core.py
```
| Before [ac319cc2]| After [e87be3e4] |   Ratio | Benchmark (Parameter)                       |
|------------------|------------------|---------|---------------------------------------------|
| 28.2±0.4ms       | 23.6±0.1ms       |    0.84 | cohorts.OISST.time_graph_construct          |
| 6.24±0.02ms      | 4.97±0.03ms      |    0.8  | cohorts.ERA5Google.time_graph_construct     |
| 294±0.8ms        | 219±4ms          |    0.75 | cohorts.ERA5Resampling.time_graph_construct |
| 42.2±0.7ms       | 29.9±0.1ms       |    0.71 | cohorts.ERA5DayOfYear.time_graph_construct  |
```
> optimize cohorts yet again

- flox/core.py
- flox/dask_array_ops.py
- tests/conftest.py
- tests/test_xarray.py
> Avoid realizing a potentially very large RangeIndex in to memory

- docs/source/user-stories/large-zonal-stats.ipynb
- flox/core.py
- flox/xrutils.py
- tests/test_core.py
Some of our reductions need more work.
> Fix sparse reindexing some more.

- flox/__init__.py
- flox/core.py
- flox/options.py
- flox/xarray.py
- tests/test_core.py
Done when
1. `method` is None
2. Grouping and reducing by a 1D array
3. `by` is sorted.
We gate this on fractional change in number of chunks and change in size of largest chunk.
Closes #359
> Auto rechunk to enable blockwise reduction
